apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hetzner-secret
  namespace: openshift-gitops
spec:
  encryptedData:
    api-key: AgCzmE5AnEZxdvJ3Ns7upG7z0UkgrqZsQkn+NPKyodhkS8jooyCTomR/BaG+7gNZE9GPTDYSBuTalnJTPwgJI2MGxJyHqa/CGwy+JDp2u/wnMHeSLemAzEeF9De8CFln0Ddcyalkkf30jhPr7GyxbNwU2n0C6c4QQ0QYBrBq/fs9w2CxuccoHTwoFY77E5wLAWvEpIj3E8Qvawo3iD2EpQjTUkJepoWHUI5tQC9gIY6c19BTGfgRvVC+AXKCVLkAy/s/nVSuodmMbJRxj24BasZU47ykcukHCyJjIczt4agPkyOecdZlsl31E5gv5Q4aTqcYfEnY40gUx9jT0ctTVkl+QcorpUgdCyWG6L3jhCrYR5s4+dfa8w/wWTr8xFLZ69iug7XVL6ehqL4/u1yoNYaxJYkEfLeCV1awkISfHeRBCJESwF3qL4Q4uu5aG9gwFuvlUaPC87+TPcWMnHwLJKSK8bMPyZ8T9ydqcf8kinykHOgEEkX2irvIPwR3J+RMOZcZ/COb4AU2a7DmbXBCuTJYcV2/nyZFeVX1FHzKy9wj2WDr3VJxu1h/4t1vlV6cxlwu3g6NwuIJX/9ze4WxVdn6ieJSlQHkHigHH2bAqfsiKteiaES9nmbCM4NtKlJTPkq+N6AOeQdY1s1AvAsWnaxTyjvaczW6ZXQE2VbUmn98G+VS94Sjn6hAamcjNFW+osDCiaGCEHKtbMxXtrW1z/NYFtPtOWpYxrtMrHDCj8S4oQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: hetzner-secret
      namespace: openshift-gitops
    type: Opaque

