apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: rzh@redhat.com 
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
      - dns01:
          webhook:
            groupName: fluentocp.wrhammers.casa
            solverName: hetzner
            config:
              secretName: hetzner-secret
              zoneName: wrhammers.casa 
              apiUrl: https://dns.hetzner.com/api/v1
