apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-webhook-hetzner
spec:
  project: cluster-config
  source:
    path: deploy/cert-manager-webhook-hetzner
    repoURL: https://github.com/vadimkim/cert-manager-webhook-hetzner
    targetRevision: master
    helm:
      values: |
        certManager:
          namespace: cert-manager-webhook
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager-webhook
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true