apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    namespace: cert-manager-webhook
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifests/configs/cert-manager/base
    repoURL: https://github.com/StinkyBenji/fluentocp-gitops
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false