apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager
spec:
  destination:
    namespace: openshift-monitoring
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifests/configs/alertmanager
    repoURL: https://github.com/StinkyBenji/fluentocp-gitops
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false